import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { PeopleService } from '../people.service';

@Component({
  selector: 'app-create',
  templateUrl: './create.page.html',
  styleUrls: ['./create.page.scss'],
})
export class CreatePage implements OnInit {

  //generated by mockaroo.com
  genderOptions = [
    'Female',
    'Male',
    'Bigender',
    'Agender',
    'Polygender',
    'Non-binary',
    'Genderfluid',
    'Genderqueer'
  ];

  personForm: FormGroup;

  constructor(private fb: FormBuilder, private ps: PeopleService, private router: Router) {
    this.personForm = this.fb.group({
      firstName: ['', Validators.required],
      lastName: ['', Validators.required],
      gender: ['', Validators.required],
      birthday: ['', Validators.required]
    });
  }

  ngOnInit() {
  }

  savePersonDetails() {
    this.ps.create(this.personForm.value);
    this.router.navigateByUrl('/');
  }

}
